# ~/.config/yazi/keymap.toml
[[mgr.prepend_keymap]]
on   = "<Enter>"
run  = [ "open", "enter" ]
desc = "Open hovered directory in $EDITOR, then cd into it"

[[mgr.prepend_keymap]]
on   = "<C-n>"
run  = 'shell "nvim" --block'
desc = "Open cwd in nvim (dashboard)"
